### ISSUE TITLE
Not compatible with document-register-element for IE11

### ISSUE THREAD

**Issue by anthony-redFox** [WebReflection/babel-plugin-transform-builtin-classes#14]
In the line ```return sPO(new Constructor, Class.prototype);```

Constructor doesn't have "this" context as Class.prototype and that why document-register-element can't get constructor from "this" statement.

The different with Reflect in the context of call ```new Constructor```

**Comment by WebReflection** [comment]
are you sure you are following instructions?
https://github.com/WebReflection/document-register-element#upgrading-the-constructor-context

**Comment by WebReflection** [comment]
just to be clear, Reflect.construct does not pass the context neither:
https://github.com/WebReflection/babel-plugin-transform-builtin-classes/blob/master/src/index.js#L9-L15

Closing this as the null context is on purpose. The constructor is bound, the new instance is created.

**Comment by anthony-redFox** [comment]
@WebReflection  Thanks  a lot!
