### ISSUE TITLE
_fixBabelExtend only injected upon first compile

### ISSUE THREAD

**Issue by wiledal** [WebReflection/babel-plugin-transform-builtin-classes#3]
Hey!

The plugin only injects the necessary `_fixBabelExtend` function on "first" compile of the source. Meaning that if the `node` thread is kept alive, using a 'watch'-command or other, the result is not as expected when the code is recompiled upon save. Assuming some `fixIsInjected`-boolean kept in memory that never resets?

I have this happening when using `gulp-watch` to trigger the task, and when just using the `--watch` flag with `babel-cli`.

Example `package.json`:
```json
{
  "dependencies": {
    "babel-plugin-transform-builtin-classes": "^0.3.2",
    "babel-preset-es2015": "^6.24.1"
  },
  "babel": {
    "presets": [
      "es2015"
    ],
    "plugins": [
      ["transform-builtin-classes", {
        "globals": [
          "HTMLElement"
        ]
      }]
    ]
  }
}
```

Example test.js:
```js
class TestComponent extends HTMLElement {
  connectedCallback () {
    // Hi
  }
}
```

Example cli command:
```bash
babel test.js -o out.js --watch
```

To get around this issue, I'm having to spawn new threads for each compile.

**Comment by oravecz** [comment]
Also causes a problem when using webpack. The `_fixBabelExtend()` helper is only included in one of the concatenated source files. The other file, wraps the HTMLElement (in my case) with `_fixBabelExtend(...)` but does not include the helper function, resulting in a `Uncaught ReferenceError: _fixBabelExtend is not defined`

**Comment by WebReflection** [comment]
so, how are you proposing to solve this?

**Comment by WebReflection** [comment]
thing is, I don't know how to always force a directive, and I thought it made sense to have the fixing code in only if native extends were used.

However, I see this as an issue but I'm not too confident with Babel internals so I'm not sure how to solve that.

**Comment by wiledal** [comment]
I know less than you about Babel plugin development, but I found this:
https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#-pre-and-post-in-plugins

I did some initial testing, and it looks like this issue can be solved by nullifying the `name` variable in the `pre`-method.
```
  return {
    pre () {
      name = null
    },
    visitor: {
      ClassDeclaration(path) {
```

**Comment by WebReflection** [comment]
can anyone please confirm v0.4 works as expected ?

Thank you @wiledal that seems to be the right way to go.

**Comment by wiledal** [comment]
Works well in my usecase!

Also, cute ✓ addition.

<img width="293" alt="screenshot 2017-09-02 19 07 14" src="https://user-images.githubusercontent.com/1035169/29997397-2e013a88-9012-11e7-94b9-355dbe531746.png">

**Comment by WebReflection** [comment]
can we close this?
