### ISSUE TITLE
[feature request] support mixins

### ISSUE THREAD

**Issue by trusktr** [WebReflection/babel-plugin-transform-builtin-classes#7]
Just opening this as a note, but I understand you might not have interest in implementing this. It'd probably take some complicated static analysis.

Another option could be to allow users to explicitly tell the plugin by writing a comment:

```js
function SomeMixin(base) {
  // @transform-builtin-classes extends HTMLElement
  return class Foo extends base { ... }
}
```

then the plugin could pick up on this cue, and it is better (IMO) than specifying a list in babelrc.

This would solve #5 and #6.

**Comment by WebReflection** [comment]
PR welcome, 'cause I don't have time for this right now.

**Comment by trusktr** [comment]
Seems like the `// @` comment option would be easier than static analysis. I like that idea.

I think I might not need this though, because I followed your caveat suggestion for `document-register-element` and am using a `construct` method (rather than `init`), so I think it should work even for native ES6+ classes extending my transpiled classes as long as they never use `constructor`. (is that right?)

**Comment by trusktr** [comment]
Oops, I missed part of your other comment:

> ```js
> function WebComponent(base) {
>   if (!base) base = class extends HTMLElement {};
>   class WebComponent extends base { ... }
> }
> ```

that would indeed work.

But do I need it for anything? If my previous guess is right, then people extending my classes can compile or not compile, and all should be fine without touching `constructor`. IIRC, this fixes direct `constructor` use.

If I were using `constructor` instead of your document-register-element caveat workaround, would users have to use this transform as well to specify my class in babelrc, when they extend my classes?

**Comment by trusktr** [comment]
I think I see: I need this transform in case document-register-element isn't loaded, because in that case the transpiled code won't work with native CE v1 even if we had followed the caveats. Is this right?

@WebReflection It may be helpful if you can write somewhere:

- In which cases using only document-register-element is fine
- In which cases to using only transform-builtin-classes is fine
- In which cases to use both transform-builtin-classes and document-register-element together

It's been hard to piece everything together by trial and error, and has taken me days of fiddling, so basically I may have forgotten some details, and you probably know it all best.

**Comment by trusktr** [comment]
For outer mixin usage, we could also do

```js
WebComponentMixin(class extends HTMLButtonElement {})
```

so I think that's good enough.
