### ISSUE TITLE
Providing a default set of native builtins?

### ISSUE THREAD

**Issue by trusktr** [WebReflection/babel-plugin-transform-builtin-classes#8]
Is there a reason not to provide a default set of builtin globals to check for? For example, `Array` and `HTMLElement` seem like a good defaults.

**Comment by WebReflection** [comment]
why does babel not transform anything by default? same reason.

You configure as you want.

**Comment by trusktr** [comment]
When I use `babel-plugin-transform-runtime` with `polyfill: true`, it seems to polyfill everything.

**Comment by WebReflection** [comment]
What is polyfill: true? 

I’ve no idea

**Comment by trusktr** [comment]
It's just proof that there is precedent for simply supporting everything rather than having people opt in to each thing individually.

`babel-plugin-transform-runtime`'s `polyfill: true` option polyfills everything in core-js (Promises, Symbols, Object.assign, Reflect, etc)

**Comment by WebReflection** [comment]
If you want to wrap most builtins extends you can use the babelrc at the root of this project, as specified in the README

https://github.com/WebReflection/babel-plugin-transform-builtin-classes/blob/master/.babelrc
